site_name: Espotifai

nav:
    - Overview: index.md
    - Related work: related_work.md
    - Project evolution: evolution.md
    - EDA: eda.md
    - Model based on track similarity: model_1/model.md
    - Model based on playlist similarity: model_2/model.md
    - Conclusion: conclusion.md

repo_url: https://github.com/lucasresck/espotifai

site_url: https://lucasresck.github.io/espotifai/
        
theme:
  name: material
  palette:
    primary: black
    scheme: default
    accent: red
  icon:
    repo: fontawesome/brands/github
  
#plugins:
#  - mkdocs-jupyter

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True
    - pymdownx.highlight:
        use_pygments: true
        linenums: false
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets
